#正式环境配置文件
server:
  port: 80
  session-timeout: 60
  tomcat:
      uri-encoding: UTF-8
spring:
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        url: jdbc:mysql://132.232.87.134:3306/wx?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&useSSL=false # 内网服务器
        username: root
        password: mhs123456%
        connection-timeout: 120000
        driver-class-name: com.mysql.jdbc.Driver
        sql-script-encoding: utf-8
        initialSize: 5 #初始化大小
        minIdle: 5 #最小
        maxActive: 100 #最大
        maxWait: 60000 #配置获取连接等待超时的时间
        timeBetweenEvictionRunsMillis: 60000 #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
        minEvictableIdleTimeMillis : 300000 #配置一个连接在池中最小生存的时间，单位是毫秒
        validationQuery: SELECT 1 FROM DUAL
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true #打开PSCache
        maxPoolPreparedStatementPerConnectionSize: 20 #指定每个连接上PSCache的大小
    http:
        multipart:
          max-file-size: 100Mb      # Max file size
          max-request-size: 100Mb   # Max request size
    redis:
      database: 0
      host: 47.93.225.125
      port: 6379
      password: 123456
      timeout: 0
      max-active: 8
      max-wait: -1
      max-idle: 8
      pool.min-idle: 0
    session:
      store-type: redis
#文件路径-生成环境下需要配置到对应的目录下
file:
  url: /tmp/bs80/data
securityconfig:
  logoutsuccssurl: /login_out
  permitall: /*/app/**,/user/web/getCode,/user/web/updateuserpassword,/user/web/updatepassword,/,/*.html,/images/**,/checkcode,/lib/**,/fonts/**,/js/**,/monitoring/findTestMacById,/testmacdata/searchTestmacData,/css/**"
  deniedpage: /deny
  urlroles: /**/new/** = admin;
            /**/edit/** = admin,editor;
            /**/delete/** = admin
